### ISSUE TITLE
Plugin not available for RIder

### ISSUE THREAD

**Issue by Bardin08** [ForNeVeR/Todosaurus#24]
### Actual:
![image](https://github.com/ForNeVeR/Todosaurus/assets/67170413/6e93c5c9-9616-4c0b-aaf7-ad21395e4dd3)

### Expected:
`Todosaurus` listed in the marketplace

### Rider Version
JetBrains Rider 2023.3.3
Build #RD-233.14015.60, built on January 18, 2024

**Comment by ForNeVeR** [comment]
It is still on under verification, that's why it's not yet available.

**Comment by Bardin08** [comment]
Got it, thanks!
